name: Test

on:
  push:
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
  pull_request:
    paths:
      - src/**
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v20.6.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.0

      - name: Install dependencies
        run: |
          npm install --global pnpm
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
